apiVersion: v1
kind: Service
metadata:
  name: responsive-website-design
spec:
  type: LoadBalancer
  selector:
    app: responsive-website-design
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080